# -*- coding: utf-8 -*-
"""new.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Barath1993/548ef917179b5e1d419fabc780ff0260/untitled28.ipynb
"""

#A single line contains integers separated by space
#Output Description:
#Print the integer list of integers separated by space
##Sample Input :
2 3 4 5 6 7 8
#Sample Output :
2 3 4 5 6 7 8



a=input()
print(a)