# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W8EZRVkVlXWtGAHxCOaK05n8H1zTQkdB
"""

#Write a code to get the input in the given format and print the output in the given format
#Input Description:
#First-line indicates two integers which are the size of array and 'K' value.
#Second-line indicates an integer contains elements of an array.
#Output Description:
#Print the taken input in the same format.
#Sample Input :
5 3
1 2 3 4 5
#Sample Output :
5 3
1 2 3 4 5





a=input()
b=input()
print(a)
print(b)